services:
  mysql:
    image: mysql:8.0
    container_name: user-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    volumes:
      - user-service-data:/var/lib/mysql

volumes:
  user-service-data:
    name: user-service-data
